version: "3"
services:
  api:
    build:
      context: .
      dockerfile: dockerfile-api
    container_name: api
    ports:
      - "8001:8001"
    networks:
      - auth-network
    restart: always
networks:
  auth-network:
  