# Stage 1: Compilar o código
FROM golang:alpine AS builder

WORKDIR /app

COPY ./src/api /app/src/api

# Utilize -ldflags para otimizar o tamanho do binário
RUN export GO111MODULE=on && cd /app/src/api/cmd && go build -ldflags="-s -w" -o main

# Stage 2: Criar uma imagem menor para a produção
FROM alpine

WORKDIR /app

# Copie apenas o executável compilado da Stage 1
COPY --from=builder /app/src/api/cmd/main /app/src/api/cmd/main

CMD ["/app/src/api/cmd/main"]
