name: CI/CD Pipeline para GCP Cloud Functions

on:
  push:
    branches:
      - test-gcp-run

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Autenticar no Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}

      - name: Configurar Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: mineral-actor-221820

      - name: Configure Docker for Artifact Registry
        run: |
          gcloud auth configure-docker us-central1-docker.pkg.dev    

      - name: Build Docker image
        run: |
          docker build -f dockerfile-api -t us-central1-docker.pkg.dev/mineral-actor-221820/your-finances/your-finances-auth:latest .   

      - name: Push Docker image to Artifact Registry
        run: |
          docker push us-central1-docker.pkg.dev/mineral-actor-221820/your-finances/your-finances-auth:latest     

      - name: Fazer deploy da Cloud Run
        run: |
           gcloud run deploy your-finances-auth-run \
            --image us-central1-docker.pkg.dev/mineral-actor-221820/your-finances/your-finances-auth:latest \
            --region us-central1 \
            --platform managed \
            --allow-unauthenticated  \
            --memory 256Mi \
            --cpu 1 \
            --max-instances 3 \
            --concurrency 5 \
            --env-vars-file env/.env.prd.yaml  
